# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [4]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [6]:
# Your code here
my_list = [1,2,3,4,5]
my_arr = np.array(my_list)

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [ ]:
# Your code here
print(my_list * 4)
print(my_arr * 4)
#With lits, the same list gets repeated four times. For arrays, each element in the array gets multiplied by four. 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 4  8 12 16 20]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [ ]:
# Your code here
print(my_list + my_list)
print(my_arr + my_arr)
print(my_arr + my_list)
#For lists, the same list gets repeated twice. For adding anything with an array,  each element is added separately.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [ ]:
# Your code here
#print(my_list - my_list)
print(my_arr - my_arr)
print(my_arr - my_list)
#For lists, it throws an error. For subtracting anything with an array,  each element is subtracted separately.

[0 0 0 0 0]
[0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [ ]:
# Your code here
#print(my_list * my_list)
print(my_arr * my_arr)
print(my_arr * my_list)
#For lists, it throws an error. For multiplying anything with an array,  each element is multiplied separately.

[ 1  4  9 16 25]
[ 1  4  9 16 25]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [ ]:
# Your code here
#print(my_list / my_list)
print(my_arr / my_arr)
print(my_arr / my_list)
#For lists, it throws an error. For dividing anything with an array,  each element is divided separately.

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [ ]:
# Your code here
#A list is treated as a single object when operators touch it, except when it is being operated on with an array. An array has elements that are treated individually. 

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [ ]:
# Your code here
def secondOfEach(input):
    #Takes in an n dimensional array and returns the second value of each row
    solution = []
    for Row in input:
        solution.append(Row[1])
    return np.array(solution)
print(secondOfEach(np.array([[1, 2, 3], [4, 5, 6]])))

[2 5]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# Your comment here
    #The numpy array iterating section was helpful in writing the for loop, it helped me search through each array of the Nd array separately. Also, the section on creating an array helped me convert the list back into an np array

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

In [ ]:
#Your code here. 
# I would do the same thing, because my method works for both ways becuase of how I treat the array/list. This demonstrates good function writing practice. 
def secondOfEach(input):
    #Takes in an n dimensional list and returns the second value of each row
    solution = []
    for Row in input:
        solution.append(Row[1])
    return np.array(solution)
print(secondOfEach([[1, 2, 3], [4, 5, 6]]))

[2 5]


## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [31]:
# Your code here
def isPrime(num):
    #Checks if number is prime
    if num <= 1:
        return False
    for i in range(2, num-1):
        if num % i == 0:
            return False
    return True

def primeElementsinArrays(input):
    #Takes in an nd array, and returns the values that are prime
    solution = []
    for r in input:
        for value in r:
            if isPrime(value):
                solution.append(value)

    return solution

primeElementsinArrays([[1,2,3],[7,7,7]])

[2, 3, 7, 7, 7]

In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [32]:
#Your code here
#Iterating Arrays
import numpy as np
#Prints each value of two arrays
arr = np.array([1, 3, 3])
arr1 = np.array([2,2,3])

for x in arr:
  print(x)
for x in arr1:
  print(x)


#Iterating Over 2D Arrays
import numpy as np
#Prints each value of two 2D arrays

arr = np.array([[1, 2, 4], [4, 5, 6]])
arr1 = np.array([[1, 3, 4], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr1:
  print(x)

#Iterating 3-D Arrays
import numpy as np

arr = np.array([[[0, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr1 = np.array([[[0, 3, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)
for x in arr1:
  print(x)

import numpy as np
#Iterates over 3D array and prints each scalar
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr1 = np.array([[[1, 2, 4], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)
for x in arr1:
  for y in x:
    for z in y:
      print(z)    

import numpy as np
#Iterating Using nditer
#Takes in multidimenisonal array and outputs each scalar using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr1 = np.array([[[1, 3], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)
for x in np.nditer(arr1):
  print(x)

import numpy as np
#Iterating over different data types
arr = np.array([1, 2, 3])
arr1 = np.array([1, 2, 4])


for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
for x in np.nditer(arr1, flags=['buffered'], op_dtypes=['S']):
  print(x)

#Iterating over different step size
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1 = np.array([[2, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)
for x in np.nditer(arr1[:, ::2]):
  print(x)

#Iterating using enumerate
import numpy as np

arr = np.array([1, 2, 3])
arr = np.array([2, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)
for idx, x in np.ndenumerate(arr1):
  print(idx, x)

import numpy as np
#Iterating on 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1 = np.array([[1, 2, 4, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)
for idx, x in np.ndenumerate(arr1):
  print(idx, x)

1
3
3
2
2
3
[1 2 4]
[4 5 6]
[1 3 4]
[4 5 6]
[[0 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[0 3 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
4
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
1
3
3
4
5
6
7
8
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'4')
1
3
5
7
2
3
5
7
(0,) 2
(1,) 2
(2,) 3
(0, 0) 2
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(0, 0) 1
(0, 1) 2
(0, 2) 4
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [ ]:
# Your comment here
#I was curious how to find primes in a multi-dimensional array, and so I sought the help of the iterating section which was very useful. Specifically, the iterating through multi-dimensional arrays inspired me. 

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [33]:
# Your code here
import even_sum

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [35]:
# Your code here
even_sum.sum_even_numbers([1,2,3,4,5])

6

I have provided you a separate module called `example.py`. Import that module here.

In [36]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [38]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [40]:
# Your code here
example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)


['Rocket left the planet!',
 'Rocket is orbiting around the planet.',
 'Rocket crashes back into the planet!']

In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [ ]:
# Your comments here
#This code has comments on every function, which is good. However, it is a bit hard to follow the logic of each function. 

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# Your comment here
#My module is about the Lagrangian function (Kinetic - potential energy). It can find the net force acting on an object given the potential energy, it can find the kinetic energy of the object, and find the Lagrangian function. 

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [ ]:
# Your comment here
#The most challenging part was learning how to take a gradient of a function in code. Now I know how to look at np documentation to figure it out

Once your module is complete, import it here.

In [2]:
# Your code here
import Lagrangian

Call each of your functions in the cell below. Make sure to show the outputs! 

In [ ]:
# Your code here
Lagrangian.findKineticEnergy([5,3], [4,2])
Lagrangian.findForces(5)
Lagrangian.findLagrangian([5,3],[5,4],5)
#Output of first call: [40, 6]. Output of second: array([], shape=(0, 3), dtype=float64) This makes sense, because it should be an empty matrix. Output of third call: [57.5, 13.0]

[57.5, 13.0]

# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!